[package]
name = "warehouse"
version = "0.1.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]

[dependencies]
iron = "0.1.21"
router = "0.0.14"
lazy_static = "0.1.14"
serde_json = "0.5.1"
hyper = "0.6.11"
